/** Section — the life of a master franchise partner, in scenes. */
export const masterLifeContent = {
  kicker: "A life, not a job",
  headline: ["What a master franchise", "partner actually does."],
  sub: "Twelve scenes from an ordinary week — the real texture of the role.",
  scenes: [
    {
      id: "own",
      index: "01",
      art: "own",
      icon: "School",
      title: "Opens his own centre first",
      line: "Before he sells a single franchise, he runs one. The model school is his proof, his training ground and his cash flow — the room he can walk any prospect through.",
      accent: "var(--coral)",
    },
    {
      id: "call",
      index: "02",
      art: "call",
      icon: "PhoneCall",
      title: "Takes the 10am call",
      line: "A franchisee two towns away has had a slow admissions week. Fifteen minutes on the phone, a look at her enquiry register, and the panic turns into a plan.",
      accent: "var(--orange)",
    },
    {
      id: "guide",
      index: "03",
      art: "guide",
      icon: "Compass",
      title: "Guides, never scolds",
      line: "He sits beside his franchisee, not across from her. Two suggestions, one deadline, a follow-up date in the diary. That is the whole management style.",
      accent: "var(--cyan)",
    },
    {
      id: "books",
      index: "04",
      art: "books",
      icon: "LineChart",
      title: "Reads his own books",
      line: "Sunday morning, one sheet. Fees collected, royalty share received, salaries out, next month's pipeline. A business he can hold in his head.",
      accent: "var(--turquoise)",
    },
    {
      id: "visit",
      index: "05",
      art: "visit",
      icon: "CarFront",
      title: "Drives out to a centre",
      line: "An hour on the highway with a coffee. He walks the classrooms, greets the teachers by name, listens to two parents at the gate — and leaves with a punch list.",
      accent: "var(--periwinkle)",
    },
    {
      id: "train",
      index: "06",
      art: "train",
      icon: "GraduationCap",
      title: "Hosts the training batch",
      line: "New teachers from three centres, one room, the Little Elly way. He organises and hosts; the company brings the curriculum and the trainers.",
      accent: "var(--pink)",
    },
    {
      id: "resolve",
      index: "07",
      art: "resolve",
      icon: "Handshake",
      title: "Settles a quiet dispute",
      line: "Two of his franchisees are chasing the same apartment complex. He redraws the catchment on a map, both keep their dignity, and the territory stays a family.",
      accent: "var(--coral)",
    },
    {
      id: "coffee",
      index: "08",
      art: "coffee",
      icon: "Coffee",
      title: "Coffee with a maybe",
      line: "A friend's wife has been thinking about a preschool for two years. No pitch deck — just a cappuccino, honest numbers, and an invitation to visit his centre.",
      accent: "var(--orange)",
    },
    {
      id: "club",
      index: "09",
      art: "club",
      icon: "Users",
      title: "Thursday at the club",
      line: "BNI, Rotary, the builders' association. Rooms full of people with capital and time, quietly looking for a business they would be proud to name at dinner.",
      accent: "var(--cyan)",
    },
    {
      id: "sign",
      index: "10",
      art: "sign",
      icon: "PenLine",
      title: "Signs a franchisee",
      line: "Number seven in his territory. One signature, one fee share, and a school that will pay him every month for the next five years.",
      accent: "var(--turquoise)",
    },
    {
      id: "event",
      index: "11",
      art: "event",
      icon: "PartyPopper",
      title: "Stands at an annual day",
      line: "Three hundred parents, a stage, small children who are not nervous. Nobody in the hall knows the word franchise. They just know the school is his.",
      accent: "var(--periwinkle)",
    },
    {
      id: "grow",
      index: "12",
      art: "grow",
      icon: "Sunrise",
      title: "Sleeps on a growing map",
      line: "Every centre he opened keeps running long after the opening ribbon. The territory compounds while he is asleep — that is the difference.",
      accent: "var(--pink)",
    },
  ],
  closing: "He isn't running a school. He's building a network.",
} as const;
